### PR TITLE
Updated the instructions for auto install

### PR DESCRIPTION
**Pull request by rakshith-ravi**
The script wouldn't work unless you cd into the directory. Updated that in the instructions.

### CODE REVIEW

**Comment by dv-anomaly** [comment]
I've gone ahead and merged this change. However it would probably be a good idea to have the script change to the directory itself.

This at the beginning of the script would do that:
```
cd "$( dirname "${BASH_SOURCE[0]}" )"
```

**Comment by rakshith-ravi** [comment]
But the problem is, what if the user is running the script inside the folder? Then cd-ing to the new folder would fail. That's why I thought it would be better to have the user cd and then run the script. I leave it to you on how to approach this

**Comment by dv-anomaly** [comment]
Actually the script would not fail with that command if it was started from within the directory, it would keep executing. That command will always `cd` to the script's root directory, even if you are already inside it.

**Comment by rakshith-ravi** [comment]
Oh wow. Never knew that command existed :sweat_smile: 
Will look into it

**Pull request merged**
